module.exports = {

    // SALES
    WAITING_FOR_PRODUCT: "WAITING_FOR_PRODUCT",
    WAITING_FOR_QUANTITY: "WAITING_FOR_QUANTITY",
    WAITING_FOR_PRICE: "WAITING_FOR_PRICE",
    WAITING_FOR_CUSTOMER: "WAITING_FOR_CUSTOMER",

    // EXPENSES
    WAITING_FOR_EXPENSE_CATEGORY: "WAITING_FOR_EXPENSE_CATEGORY",
    WAITING_FOR_EXPENSE_DESCRIPTION: "WAITING_FOR_EXPENSE_DESCRIPTION",
    WAITING_FOR_EXPENSE_AMOUNT: "WAITING_FOR_EXPENSE_AMOUNT",
    WAITING_FOR_EXPENSE_NOTE: "WAITING_FOR_EXPENSE_NOTE",

    // INCOME
    WAITING_FOR_INCOME_SOURCE: "WAITING_FOR_INCOME_SOURCE",
    WAITING_FOR_INCOME_AMOUNT: "WAITING_FOR_INCOME_AMOUNT",
    WAITING_FOR_INCOME_NOTE: "WAITING_FOR_INCOME_NOTE"

};