const {
    buildForecast
} = require("./forecasting/forecastEngine");

// ==========================
// BUSINESS FORECAST
// ==========================
//
// Central interface between the Forecast Engine and
// higher-level intelligence services.
//
// The Forecast Engine is the single source of truth for:
//
// - Revenue forecast
// - Cash forecast
// - Inventory forecast
// - Inventory demand forecast
// - Profit forecast
// - Risks
// - Decisions
// - Recommendations
// - Advisor assessment
//
// This service does NOT calculate or reinterpret any of
// those values.
//
// It simply exposes the complete intelligence structure
// through a stable interface for:
//
// - Executive Reports
// - AI Advisor
// - Telegram
// - Future Web Dashboard
// - Future Mobile App
//
// ==========================

function getBusinessForecast(
    telegramId
) {

    const forecast =
        buildForecast(
            telegramId
        );


    // ==================================================
    // PROJECTED REVENUE
    // ==================================================
    //
    // Revenue Forecast Engine returns:
    //
    // forecast.revenue.tomorrow
    //
    // ==================================================

    const projectedRevenue =
        Number(
            forecast
                ?.revenue
                ?.tomorrow
        ) || 0;


    // ==================================================
    // PROJECTED PROFIT
    // ==================================================
    //
    // Profit Forecast Engine returns:
    //
    // forecast.profit.tomorrowProfit
    //
    // ==================================================

    const projectedProfit =
        Number(
            forecast
                ?.profit
                ?.tomorrowProfit
        ) || 0;


    // ==================================================
    // FORECAST CONFIDENCE
    // ==================================================

    const confidence =
        Number(
            forecast
                ?.revenue
                ?.confidence
        ) || 0;


    // ==================================================
    // RETURN COMPLETE BUSINESS INTELLIGENCE
    // ==================================================

    return {

        // ------------------------------------------------
        // CORE FORECASTS
        // ------------------------------------------------

        revenue:
            forecast.revenue,

        cash:
            forecast.cash,

        inventory:
            forecast.inventory,

        inventoryDemand:
            forecast.inventoryDemand,

        profit:
            forecast.profit,


        // ------------------------------------------------
        // NORMALIZED PROJECTED VALUES
        // ------------------------------------------------

        projectedRevenue,

        projectedProfit,

        confidence,


        // ------------------------------------------------
        // RISK INTELLIGENCE
        // ------------------------------------------------

        risks:
            forecast.risks,


        // ------------------------------------------------
        // DECISIONS
        // ------------------------------------------------

        decisions:
            forecast.decisions,


        // ------------------------------------------------
        // RECOMMENDATIONS
        // ------------------------------------------------
        //
        // These are generated by the central
        // Recommendation Engine through Forecast Engine.
        //
        // No duplicate recommendation logic is created here.
        //

        recommendations:
            forecast.recommendations,


        // ------------------------------------------------
        // ADVISOR CORE
        // ------------------------------------------------
        //
        // Advisor Core interprets the complete business
        // intelligence and produces:
        //
        // - businessStatus
        // - overallPriority
        // - headline
        // - assessment
        // - keyIssues
        // - opportunities
        // - recommendedActions
        // - confidence
        //
        // ------------------------------------------------

        advisor:
            forecast.advisor,


        // ------------------------------------------------
        // EXECUTIVE SUMMARY
        // ------------------------------------------------

        executiveSummary:
            forecast.executiveSummary,


        // ------------------------------------------------
        // HISTORICAL SUPPORTING DATA
        // ------------------------------------------------

        expenseHistory:
            forecast.expenseHistory,

        cogsHistory:
            forecast.cogsHistory

    };

}


// ==========================
// EXPORT
// ==========================

module.exports = {

    getBusinessForecast

};