const analytics = require("./financialAnalyticsService");
const kpiService = require("./businessKPIService");
const trendService = require("./businessTrendsService");
const forecastService = require("./businessForecastService");
const insightsService = require("./businessInsightsService");
const profitLossService = require("./profitLossService");
const cashFlowService = require("./cashFlowService");

// ==========================
// EXECUTIVE REPORT
// ==========================
//
// Presentation-ready aggregation layer.
//
// IMPORTANT:
//
// This service does NOT calculate:
//
// - Revenue
// - Profit
// - Cash
// - Inventory
// - Risks
// - Decisions
// - Recommendations
// - Advisor intelligence
//
// Those responsibilities already belong to the
// underlying services and intelligence engines.
//
// This service simply assembles them into one
// Executive Report structure for:
//
// - Telegram
// - PDF export
// - Excel export
// - Web dashboard
// - Mobile app
// - Future AI CFO interface
// ==========================

function getExecutiveReport(telegramId) {

    // ==================================================
    // CORE BUSINESS DATA
    // ==================================================

    const dashboard =
        analytics.getBusinessSnapshot(
            telegramId
        );

    const health =
        analytics.getBusinessHealth(
            telegramId
        );

    const kpis =
        kpiService.getBusinessKPIs(
            telegramId
        );

    const trends =
        trendService.getBusinessTrends(
            telegramId
        );

    const forecast =
        forecastService.getBusinessForecast(
            telegramId
        );

    const insights =
        insightsService.getBusinessInsights(
            telegramId
        );

    const profitLoss =
        profitLossService.getProfitLoss(
            telegramId
        );

    const cashFlow =
        cashFlowService.getCashFlow(
            telegramId
        );


    // ==================================================
    // ADVISOR INTELLIGENCE
    // ==================================================
    //
    // Advisor Core is already generated inside the
    // Forecast Engine.
    //
    // We expose it here instead of recalculating it.

    const advisor =
        forecast?.advisor || {

            businessStatus:
                "Unknown",

            overallPriority:
                "Low",

            headline:
                "No advisor assessment available.",

            assessment:
                "No advisor assessment is currently available.",

            keyIssues: [],

            opportunities: [],

            recommendedActions: [],

            confidence: 0,

            sourceData: {

                risks: [],

                decisions: []

            }

        };


    // ==================================================
    // TOP DECISION
    // ==================================================
    //
    // The Recommendation Engine already receives the
    // decisions generated by the Decision Engine.
    //
    // We expose the highest-priority decision for the
    // Executive Report.

    const decisions =
        Array.isArray(
            forecast?.decisions
        )
            ? forecast.decisions
            : [];


    const topDecision =
        decisions.length > 0
            ? decisions[0]
            : null;


    // ==================================================
    // TOP RECOMMENDATION
    // ==================================================

    const recommendations =
        Array.isArray(
            forecast?.recommendations
        )
            ? forecast.recommendations
            : [];


    const topRecommendation =
        recommendations.length > 0
            ? recommendations[0]
            : null;


    // ==================================================
    // RETURN EXECUTIVE REPORT
    // ==================================================

    return {

        // ------------------------------------------------
        // BUSINESS OVERVIEW
        // ------------------------------------------------

        dashboard,

        health,


        // ------------------------------------------------
        // KPI
        // ------------------------------------------------

        kpis,


        // ------------------------------------------------
        // TRENDS
        // ------------------------------------------------

        trends,


        // ------------------------------------------------
        // FORECAST
        // ------------------------------------------------

        forecast,


        // ------------------------------------------------
        // PROFIT & LOSS
        // ------------------------------------------------

        profitLoss,


        // ------------------------------------------------
        // CASH FLOW
        // ------------------------------------------------

        cashFlow,


        // ------------------------------------------------
        // BUSINESS INSIGHTS
        // ------------------------------------------------

        insights,


        // ------------------------------------------------
        // RISK INTELLIGENCE
        // ------------------------------------------------

        risks:
            forecast?.risks || [],


        // ------------------------------------------------
        // DECISION INTELLIGENCE
        // ------------------------------------------------

        decisions,

        topDecision,


        // ------------------------------------------------
        // RECOMMENDATION INTELLIGENCE
        // ------------------------------------------------

        recommendations,

        topRecommendation,


        // ------------------------------------------------
        // ADVISOR CORE
        // ------------------------------------------------

        advisor,


        // ------------------------------------------------
        // EXECUTIVE SUMMARY
        // ------------------------------------------------

        executiveSummary:
            forecast?.executiveSummary ||
            advisor.assessment ||
            "No executive summary is currently available."

    };
}


// ==========================
// EXPORT
// ==========================

module.exports = {

    getExecutiveReport

};