module.exports = {

    // ==========================
    // SALES
    // ==========================
    WAITING_FOR_PRODUCT: "WAITING_FOR_PRODUCT",
    WAITING_FOR_QUANTITY: "WAITING_FOR_QUANTITY",
    WAITING_FOR_PRICE: "WAITING_FOR_PRICE",
    WAITING_FOR_CUSTOMER: "WAITING_FOR_CUSTOMER",
    WAITING_FOR_PAYMENT_STATUS: "WAITING_FOR_PAYMENT_STATUS",

    // ==========================
    // EXPENSES
    // ==========================
    WAITING_FOR_EXPENSE_CATEGORY: "WAITING_FOR_EXPENSE_CATEGORY",
    WAITING_FOR_EXPENSE_DESCRIPTION: "WAITING_FOR_EXPENSE_DESCRIPTION",
    WAITING_FOR_EXPENSE_AMOUNT: "WAITING_FOR_EXPENSE_AMOUNT",
    WAITING_FOR_EXPENSE_NOTE: "WAITING_FOR_EXPENSE_NOTE",

    // ==========================
    // INCOME
    // ==========================
    WAITING_FOR_INCOME_SOURCE: "WAITING_FOR_INCOME_SOURCE",
    WAITING_FOR_INCOME_AMOUNT: "WAITING_FOR_INCOME_AMOUNT",
    WAITING_FOR_INCOME_NOTE: "WAITING_FOR_INCOME_NOTE",

    // ==========================
    // CUSTOMERS
    // ==========================
    WAITING_FOR_CUSTOMER_NAME: "WAITING_FOR_CUSTOMER_NAME",
    WAITING_FOR_CUSTOMER_PHONE: "WAITING_FOR_CUSTOMER_PHONE",
    WAITING_FOR_CUSTOMER_EMAIL: "WAITING_FOR_CUSTOMER_EMAIL",
    WAITING_FOR_CUSTOMER_ADDRESS: "WAITING_FOR_CUSTOMER_ADDRESS",
    WAITING_FOR_CUSTOMER_SEARCH: "WAITING_FOR_CUSTOMER_SEARCH",

    // ==========================
    // INVENTORY
    // ==========================
    WAITING_FOR_INVENTORY_PRODUCT: "WAITING_FOR_INVENTORY_PRODUCT",
    WAITING_FOR_INVENTORY_QUANTITY: "WAITING_FOR_INVENTORY_QUANTITY",
    WAITING_FOR_COST_PRICE: "WAITING_FOR_COST_PRICE",
    WAITING_FOR_SELLING_PRICE: "WAITING_FOR_SELLING_PRICE",

    // ==========================
    // DEBTORS
    // ==========================
    WAITING_FOR_PAYMENT_CUSTOMER: "WAITING_FOR_PAYMENT_CUSTOMER",
    WAITING_FOR_PAYMENT_AMOUNT: "WAITING_FOR_PAYMENT_AMOUNT",

    // ==========================
    // SUPPLIERS
    // ==========================
    WAITING_FOR_SUPPLIER_NAME: "WAITING_FOR_SUPPLIER_NAME",
    WAITING_FOR_SUPPLIER_PHONE: "WAITING_FOR_SUPPLIER_PHONE",
    WAITING_FOR_SUPPLIER_EMAIL: "WAITING_FOR_SUPPLIER_EMAIL",
    WAITING_FOR_SUPPLIER_ADDRESS: "WAITING_FOR_SUPPLIER_ADDRESS",
    WAITING_FOR_SUPPLIER_SEARCH: "WAITING_FOR_SUPPLIER_SEARCH"

};