module.exports = {

    
// ======================================================
// SALES
// ======================================================

WAITING_FOR_PRODUCT:
    "WAITING_FOR_PRODUCT",

WAITING_FOR_QUANTITY:
    "WAITING_FOR_QUANTITY",

WAITING_FOR_PRICE:
    "WAITING_FOR_PRICE",

WAITING_FOR_CUSTOMER:
    "WAITING_FOR_CUSTOMER",

WAITING_FOR_PAYMENT_STATUS:
    "WAITING_FOR_PAYMENT_STATUS",


// ======================================================
// BUSINESS EXPENSES
// ======================================================

WAITING_FOR_EXPENSE_CATEGORY:
    "WAITING_FOR_EXPENSE_CATEGORY",

WAITING_FOR_EXPENSE_DESCRIPTION:
    "WAITING_FOR_EXPENSE_DESCRIPTION",

WAITING_FOR_EXPENSE_AMOUNT:
    "WAITING_FOR_EXPENSE_AMOUNT",

WAITING_FOR_EXPENSE_NOTE:
    "WAITING_FOR_EXPENSE_NOTE",


// ======================================================
// BUSINESS INCOME
// ======================================================

WAITING_FOR_INCOME_SOURCE:
    "WAITING_FOR_INCOME_SOURCE",

WAITING_FOR_INCOME_AMOUNT:
    "WAITING_FOR_INCOME_AMOUNT",

WAITING_FOR_INCOME_NOTE:
    "WAITING_FOR_INCOME_NOTE",


// ======================================================
// CUSTOMERS
// ======================================================

WAITING_FOR_CUSTOMER_NAME:
    "WAITING_FOR_CUSTOMER_NAME",

WAITING_FOR_CUSTOMER_PHONE:
    "WAITING_FOR_CUSTOMER_PHONE",

WAITING_FOR_CUSTOMER_EMAIL:
    "WAITING_FOR_CUSTOMER_EMAIL",

WAITING_FOR_CUSTOMER_ADDRESS:
    "WAITING_FOR_CUSTOMER_ADDRESS",

WAITING_FOR_CUSTOMER_SEARCH:
    "WAITING_FOR_CUSTOMER_SEARCH",


// ======================================================
// INVENTORY
// ======================================================

WAITING_FOR_INVENTORY_PRODUCT:
    "WAITING_FOR_INVENTORY_PRODUCT",

WAITING_FOR_INVENTORY_QUANTITY:
    "WAITING_FOR_INVENTORY_QUANTITY",

WAITING_FOR_COST_PRICE:
    "WAITING_FOR_COST_PRICE",

WAITING_FOR_SELLING_PRICE:
    "WAITING_FOR_SELLING_PRICE",


// ======================================================
// BUSINESS DEBTORS
// ======================================================

WAITING_FOR_PAYMENT_CUSTOMER:
    "WAITING_FOR_PAYMENT_CUSTOMER",

WAITING_FOR_PAYMENT_AMOUNT:
    "WAITING_FOR_PAYMENT_AMOUNT",


// ======================================================
// SUPPLIERS
// ======================================================

WAITING_FOR_SUPPLIER_NAME:
    "WAITING_FOR_SUPPLIER_NAME",

WAITING_FOR_SUPPLIER_PHONE:
    "WAITING_FOR_SUPPLIER_PHONE",

WAITING_FOR_SUPPLIER_EMAIL:
    "WAITING_FOR_SUPPLIER_EMAIL",

WAITING_FOR_SUPPLIER_ADDRESS:
    "WAITING_FOR_SUPPLIER_ADDRESS",

WAITING_FOR_SUPPLIER_SEARCH:
    "WAITING_FOR_SUPPLIER_SEARCH",


// ======================================================
// CREDITORS
// ======================================================

WAITING_FOR_CREDITOR_SUPPLIER:
    "WAITING_FOR_CREDITOR_SUPPLIER",

WAITING_FOR_CREDITOR_PAYMENT:
    "WAITING_FOR_CREDITOR_PAYMENT",


// ======================================================
// PURCHASES
// ======================================================

WAITING_FOR_PURCHASE_SUPPLIER:
    "WAITING_FOR_PURCHASE_SUPPLIER",

WAITING_FOR_PURCHASE_PRODUCT:
    "WAITING_FOR_PURCHASE_PRODUCT",

WAITING_FOR_PURCHASE_QUANTITY:
    "WAITING_FOR_PURCHASE_QUANTITY",

WAITING_FOR_PURCHASE_COST:
    "WAITING_FOR_PURCHASE_COST",

WAITING_FOR_PURCHASE_PAID:
    "WAITING_FOR_PURCHASE_PAID",


// ======================================================
// PERSONAL INCOME
// ======================================================

WAITING_FOR_PERSONAL_INCOME_SOURCE:
    "WAITING_FOR_PERSONAL_INCOME_SOURCE",

WAITING_FOR_PERSONAL_INCOME_AMOUNT:
    "WAITING_FOR_PERSONAL_INCOME_AMOUNT",

WAITING_FOR_PERSONAL_INCOME_NOTE:
    "WAITING_FOR_PERSONAL_INCOME_NOTE",


// ======================================================
// PERSONAL EXPENSES
// ======================================================

WAITING_FOR_PERSONAL_EXPENSE_CATEGORY:
    "WAITING_FOR_PERSONAL_EXPENSE_CATEGORY",

WAITING_FOR_PERSONAL_EXPENSE_DESCRIPTION:
    "WAITING_FOR_PERSONAL_EXPENSE_DESCRIPTION",

WAITING_FOR_PERSONAL_EXPENSE_AMOUNT:
    "WAITING_FOR_PERSONAL_EXPENSE_AMOUNT",

WAITING_FOR_PERSONAL_EXPENSE_NOTE:
    "WAITING_FOR_PERSONAL_EXPENSE_NOTE",


// ======================================================
// PERSONAL DEBTS
// Money the user OWES to someone else.
// ======================================================

WAITING_FOR_PERSONAL_DEBT_NAME:
    "WAITING_FOR_PERSONAL_DEBT_NAME",

WAITING_FOR_PERSONAL_DEBT_AMOUNT:
    "WAITING_FOR_PERSONAL_DEBT_AMOUNT",

WAITING_FOR_PERSONAL_DEBT_DUE_DATE:
    "WAITING_FOR_PERSONAL_DEBT_DUE_DATE",

WAITING_FOR_PERSONAL_DEBT_NOTE:
    "WAITING_FOR_PERSONAL_DEBT_NOTE",

WAITING_FOR_PERSONAL_DEBT_PAYMENT_DEBT:
    "WAITING_FOR_PERSONAL_DEBT_PAYMENT_DEBT",

WAITING_FOR_PERSONAL_DEBT_PAYMENT_AMOUNT:
    "WAITING_FOR_PERSONAL_DEBT_PAYMENT_AMOUNT",

WAITING_FOR_PERSONAL_DEBT_UPDATE_DEBT:
    "WAITING_FOR_PERSONAL_DEBT_UPDATE_DEBT",

WAITING_FOR_PERSONAL_DEBT_UPDATE_FIELD:
    "WAITING_FOR_PERSONAL_DEBT_UPDATE_FIELD",

WAITING_FOR_PERSONAL_DEBT_UPDATE_VALUE:
    "WAITING_FOR_PERSONAL_DEBT_UPDATE_VALUE",

WAITING_FOR_PERSONAL_DEBT_COMPLETE:
    "WAITING_FOR_PERSONAL_DEBT_COMPLETE",

WAITING_FOR_PERSONAL_DEBT_DELETE:
    "WAITING_FOR_PERSONAL_DEBT_DELETE",


// ======================================================
// PERSONAL DEBTORS
// Money OTHER PEOPLE owe to the user.
// ======================================================

WAITING_FOR_PERSONAL_DEBTOR_NAME:
    "WAITING_FOR_PERSONAL_DEBTOR_NAME",

WAITING_FOR_PERSONAL_DEBTOR_AMOUNT:
    "WAITING_FOR_PERSONAL_DEBTOR_AMOUNT",

WAITING_FOR_PERSONAL_DEBTOR_NOTE:
    "WAITING_FOR_PERSONAL_DEBTOR_NOTE",

WAITING_FOR_PERSONAL_DEBTOR_VIEW:
    "WAITING_FOR_PERSONAL_DEBTOR_VIEW",

WAITING_FOR_PERSONAL_DEBTOR_PAYMENT_DEBT:
    "WAITING_FOR_PERSONAL_DEBTOR_PAYMENT_DEBT",

WAITING_FOR_PERSONAL_DEBTOR_PAYMENT_AMOUNT:
    "WAITING_FOR_PERSONAL_DEBTOR_PAYMENT_AMOUNT",

WAITING_FOR_PERSONAL_DEBTOR_UPDATE_DEBT:
    "WAITING_FOR_PERSONAL_DEBTOR_UPDATE_DEBT",

WAITING_FOR_PERSONAL_DEBTOR_UPDATE_FIELD:
    "WAITING_FOR_PERSONAL_DEBTOR_UPDATE_FIELD",

WAITING_FOR_PERSONAL_DEBTOR_UPDATE_VALUE:
    "WAITING_FOR_PERSONAL_DEBTOR_UPDATE_VALUE",

WAITING_FOR_PERSONAL_DEBTOR_COMPLETE:
    "WAITING_FOR_PERSONAL_DEBTOR_COMPLETE",

WAITING_FOR_PERSONAL_DEBTOR_DELETE:
    "WAITING_FOR_PERSONAL_DEBTOR_DELETE",

WAITING_FOR_PERSONAL_DEBTOR_SUMMARY:
    "WAITING_FOR_PERSONAL_DEBTOR_SUMMARY",


// ======================================================
// PERSONAL SAVINGS
// ======================================================

WAITING_FOR_PERSONAL_SAVINGS:
    "WAITING_FOR_PERSONAL_SAVINGS",


// ======================================================
// PERSONAL CASH FLOW
// ======================================================

WAITING_FOR_PERSONAL_CASH_FLOW:
    "WAITING_FOR_PERSONAL_CASH_FLOW",


// ======================================================
// PERSONAL FINANCIAL REPORTS
// ======================================================

WAITING_FOR_PERSONAL_REPORT:
    "WAITING_FOR_PERSONAL_REPORT",


// ======================================================
// PERSONAL FORECAST
// ======================================================

WAITING_FOR_PERSONAL_FORECAST:
    "WAITING_FOR_PERSONAL_FORECAST",


// ======================================================
// PERSONAL AI FINANCIAL ADVISOR
// ======================================================

WAITING_FOR_PERSONAL_ADVISOR:
    "WAITING_FOR_PERSONAL_ADVISOR"


};